In [1]:
import sys
from PyQt5.QtWidgets import QApplication, QWidget
from napari_gui import Window, Viewer

import numpy as np

from skimage import data

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import matplotlib.pyplot as plt

/Users/bryant.chhun/anaconda3/envs/ReconOrder/lib/python3.7/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")


In [4]:
im = data.astronaut()

In [5]:
im.shape
type(im)
np.max(im)
np.min(im)

(512, 512, 3)

numpy.ndarray

255

0

In [6]:
randim = np.random.random_integers(0,255, size=(512,512))

/Users/bryant.chhun/anaconda3/envs/InstantPol3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 255 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
plt.imshow(randim)

In [14]:
#=========== Vispy tests =================================

In [5]:
from vispy import app, gloo, visuals
from vispy.visuals.transforms import STTransform, NullTransform


In [6]:
# vertex positions of data to draw
N = 20
pos = np.zeros((N, 2), dtype=np.float32)
pos[:, 0] = np.linspace(10, 390, N)
pos[:, 1] = np.random.normal(size=N, scale=20, loc=0)

# color array
color = np.ones((N, 4), dtype=np.float32)
color[:, 0] = np.linspace(0, 1, N)
color[:, 1] = color[::-1, 0]

# connection array
# connect = np.empty((N-1, 2), np.int32)
# connect[:, 0] = np.arange(N-1)
# connect[:, 1] = connect[:, 0] + 1
# connect[N//2, 1] = N//2  # put a break in the middle
connect='segments'

In [7]:
pos.shape

(20, 2)

In [37]:
pos[0]

array([ 10.      , -35.461082], dtype=float32)

In [15]:
nx, ny = (20, 20)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)

In [24]:
n = 20
dim = np.linspace(0,19,n)
dim

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [26]:
xv, yv = np.meshgrid(dim, dim)
xv
yv

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
         2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
         4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
         6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,
         7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  

In [55]:
N=20
pos2 = np.zeros((400, 2), dtype=np.float32)
pos2.shape

(400, 2)

In [57]:
pos2[:,0] = xv.flatten()
pos2[:,1] = yv.flatten()

In [79]:
pos2[::2,1] += 1

In [80]:
pos2[0]
pos2[1]
pos2[2]

array([0., 2.], dtype=float32)

array([1., 0.], dtype=float32)

array([2., 1.], dtype=float32)

In [81]:
[pos2[k] for k in range(0,20)]

[array([0., 2.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([2., 1.], dtype=float32),
 array([3., 0.], dtype=float32),
 array([4., 1.], dtype=float32),
 array([5., 0.], dtype=float32),
 array([6., 1.], dtype=float32),
 array([7., 0.], dtype=float32),
 array([8., 1.], dtype=float32),
 array([9., 0.], dtype=float32),
 array([10.,  1.], dtype=float32),
 array([11.,  0.], dtype=float32),
 array([12.,  1.], dtype=float32),
 array([13.,  0.], dtype=float32),
 array([14.,  1.], dtype=float32),
 array([15.,  0.], dtype=float32),
 array([16.,  1.], dtype=float32),
 array([17.,  0.], dtype=float32),
 array([18.,  1.], dtype=float32),
 array([19.,  0.], dtype=float32)]

In [2]:
k1 = "1x1"
k2 = "2x2"

In [4]:
test = {"1x1":(1,1)}

In [2]:
xdim = 20
ydim = 20

pos = np.zeros((4*xdim*ydim, 2), dtype=np.float32)

In [ ]:
xspace = np.linspace(0, xdim-1, 2*xdim)
yspace = np.linspace(0, ydim-1, 2*ydim)
xv, yv = np.meshgrid(xspace, yspace)

1600

In [ ]:
len(xspace)
len(yspace)

40